## 9.1 - Estrutura de dados no Pandas

*Series* - *Series* são estruturas de dados 1D e podem ser criadas a partir de dicionários, arrays, entre outros. É muito parecido com os arrays em termos de propriedades e métodos.
- pd.Series(data, index=index)

In [126]:
lista_a = [11,22,33,44,55]
lista_b = ['a','b','c','d','e']

import pandas as pd

In [127]:
serie_1 = pd.Series(lista_a)
print(serie_1)

0    11
1    22
2    33
3    44
4    55
dtype: int64


In [128]:
serie_2 = pd.Series(lista_a)
print(serie_2[4])

55


In [129]:
serie_3 = pd.Series(lista_a)
print(serie_3.shape)

(5,)


In [130]:
serie_4 = pd.Series(lista_a)
print(serie_4.ndim)

1


In [131]:
serie_5 = pd.Series(lista_a)
print(serie_4.size)

5


In [132]:
serie_6 = pd.Series(lista_a)
print(serie_6.cumsum())

0     11
1     33
2     66
3    110
4    165
dtype: int64


In [133]:
serie_7 = pd.Series(lista_a)
print(serie_7.mean())

33.0


In [134]:
serie_8 = pd.Series(lista_a,index=lista_b)
print(serie_8)

a    11
b    22
c    33
d    44
e    55
dtype: int64


In [135]:
serie_9 = pd.Series(lista_a,index=lista_b)
print(serie_9['b'])

22


In [136]:
serie_10 = pd.Series(lista_b,index=lista_a)
print(serie_10)

11    a
22    b
33    c
44    d
55    e
dtype: object


In [137]:
serie_11 = pd.Series(lista_b,index=lista_a)
print(serie_11[22])

b


In [138]:
import numpy as np

arr = np.arange(10)**2

dic = {'a':123,'b':456,'c':789}

In [139]:
serie_12 = pd.Series(arr)
print(serie_12)

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64


In [140]:
serie_13 = pd.Series(dic)
print(serie_13)

a    123
b    456
c    789
dtype: int64


In [141]:
serie_14 = pd.Series(dic)
print(serie_14['b'])

456


*DataFrame* - *DataFrames* são estruturas de dados 2D e podem ser criadas a partir de dicionários, dados estruturados em 2D, arquivos csv, etc. Em resumo, DataFrame é uma **tabela**.
- pd.DataFrame({'key_1': pd.Series(...), 'key_n':pd.Series(...)})
- pd.read_csv(file)

In [142]:
dic2 = {'coluna1':np.arange(10)*5,'coluna2':np.arange(10)**2,'coluna3':np.ones(10)}
dic2

{'coluna1': array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]),
 'coluna2': array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]),
 'coluna3': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}

In [143]:
dic2 = {'coluna1':np.arange(10)*5,'coluna2':np.arange(10)**2,'coluna3':np.ones(10)}
dic2['coluna2']

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [144]:
df1 = pd.DataFrame(dic2)
print(df1) ## type(df1) = pandas.core.frame.DataFrame

   coluna1  coluna2  coluna3
0        0        0      1.0
1        5        1      1.0
2       10        4      1.0
3       15        9      1.0
4       20       16      1.0
5       25       25      1.0
6       30       36      1.0
7       35       49      1.0
8       40       64      1.0
9       45       81      1.0


In [145]:
df1 = pd.DataFrame(dic2)
print(df1['coluna2']) ##type(df1['coluna2']) = pandas.core.series.Series

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
Name: coluna2, dtype: int64


In [146]:
arr2 = np.arange(15).reshape(5,3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [147]:
df2 = pd.DataFrame(arr2)
print(df2)

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14


In [150]:
file = 'datasets_1358_30676_Players.csv'

NBA_players = pd.read_csv(file)
NBA_players

Unnamed: 0             Player  height  weight  \
0              0    Curly Armstrong   180.0    77.0   
1              1       Cliff Barker   188.0    83.0   
2              2      Leo Barnhorst   193.0    86.0   
3              3         Ed Bartels   196.0    88.0   
4              4        Ralph Beard   178.0    79.0   
...          ...                ...     ...     ...   
3917        3917      Troy Williams   198.0    97.0   
3918        3918       Kyle Wiltjer   208.0   108.0   
3919        3919  Stephen Zimmerman   213.0   108.0   
3920        3920        Paul Zipser   203.0    97.0   
3921        3921        Ivica Zubac   216.0   120.0   

                              collage    born      birth_city  \
0                  Indiana University  1918.0             NaN   
1              University of Kentucky  1921.0        Yorktown   
2            University of Notre Dame  1924.0             NaN   
3     North Carolina State University  1925.0             NaN   
4              University of Kentucky  1927.0     Hardinsburg   
...                               ...     ...             ...   
3917  South Carolina State University  1969.0        Columbia   
3918               Gonzaga University  1992.0        Portland   
3919  University of Nevada, Las Vegas  1996.0  Hendersonville   
3920                              NaN  1994.0      Heidelberg   
3921                              NaN  1997.0          Mostar   

                 birth_state  
0                        NaN  
1                    Indiana  
2                        NaN  
3                        NaN  
4                   Kentucky  
...                      ...  
3917          South Carolina  
3918                  Oregon  
3919               Tennessee  
3920                 Germany  
3921  Bosnia and Herzegovina  

[3922 rows x 8 columns]